#!/bin/sh
sudo cp $HOME/temp/MyChronoGPS/MyChronoGPS.py $HOME/MyChronoGPS/MyChronoGPS.py
sudo cp $HOME/temp/MyChronoGPS/MyChronoGPS.sh $HOME/MyChronoGPS/MyChronoGPS.sh
sudo cp $HOME/temp/MyChronoGPS/MyChronoGPS_GoogleMaps.sh $HOME/MyChronoGPS/MyChronoGPS_GoogleMaps.sh
sudo cp $HOME/temp/MyChronoGPS/MyChronoGPS_Leaflet.sh $HOME/MyChronoGPS/MyChronoGPS_Leaflet.sh
sudo cp $HOME/temp/MyChronoGPS/VERSION $HOME/MyChronoGPS/VERSION
sudo cp $HOME/temp/MyChronoGPS/Web-Pi $HOME/MyChronoGPS -r
sudo cp $HOME/MyChronoGPS/tracks $HOME/MyChronoGPS/save-tracks -r
sudo cp $HOME/temp/MyChronoGPS/tracks $HOME/MyChronoGPS -r

sudo chown -R www-data:www-data $HOME/MyChronoGPS

sudo chmod -R u+wx,g+wx,o+wx $HOME/MyChronoGPS
